version: "3"
services:
  media_service_database:
    container_name: media_service_db
    image: postgres:9.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "media_service_db"
      POSTGRES_USER: "cotlin_user"
      POSTGRES_PASSWORD: "cotlin_password"

  redis:
    image: redis:alpine
    command: redis-server --port 63790
    container_name: redis_boot
    hostname: redis_boot
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - "63790:63790"