server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/media_service_db
    username: cotlin_user
    password: cotlin_password
  exposed:
    show-sql: true
  redis:
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
    port: 63790
    host: 127.0.0.1

  config:
    import: classpath:email-config.yml

JWT:
  access_secret: media_service_secret_authorization_jwt_token_media_service_secret_authorization_jwt_token
  refresh_secret: media_service_secret_authorization_refresh_token_media_service_secret_authorization_refresh_token